name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Cache Prolog
      uses: actions/cache@v2
      id: cache-prolog
      with:
        path: "~/prolog"
        key: cache-pl-packages

    - name: test
      run: |
       swipl -f hello_world.pl -s hello_world_tests.plt -g run_tests,halt -t 'halt(1)'
