name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Prolog download
      run: | 
            sudo apt-add-repository ppa:swi-prolog/devel -y
            sudo apt-get update -q
            sudo apt-get install swi-prolog-nox
    
    - name: test
      run: |
        sh -c "$(cat run_tests.bat)"
