name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Install Trealla ProLog
      uses: logtalk-actions/setup-trealla-prolog@master
      with:
        trealla-prolog-branch: devel
        trealla-prolog-version: latest

    - name: test
      run: |
       cat run_tests.bat | xargs
